# Generated by Django 4.2.23 on 2025-08-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import onboarding.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Department Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="This slug is used when building request IDs. Once set, try not to change it as it may cause confusion.",
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="All outgoing e-mails for this department will use this e-mail address.",
                        max_length=254,
                        null=True,
                        verbose_name="Department E-Mail Address",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this department's role in onboarding.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this department is actively handling onboarding requests.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "auto_assign_to_manager",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically assign new requests to the department manager.",
                        verbose_name="Auto-assign to Manager",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Manager responsible for this department's onboarding tasks.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Department Manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="OnboardingRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the onboarding request",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date this request was first created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date this request was most recently changed",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "new_hire_name",
                    models.CharField(
                        help_text="Full name of the person being onboarded",
                        max_length=200,
                        verbose_name="New Hire Name",
                    ),
                ),
                (
                    "new_hire_email",
                    models.EmailField(
                        help_text="Email address of the new hire",
                        max_length=254,
                        verbose_name="New Hire E-Mail",
                    ),
                ),
                (
                    "new_hire_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number for the new hire",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Job title or position for the new hire",
                        max_length=200,
                        verbose_name="Position/Role",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="Expected or actual start date for the new hire",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "hiring_manager",
                    models.CharField(
                        help_text="Name of the hiring manager or supervisor",
                        max_length=200,
                        verbose_name="Hiring Manager",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Pending"),
                            (2, "In Progress"),
                            (3, "Waiting for Information"),
                            (4, "Completed"),
                            (5, "Cancelled"),
                        ],
                        default=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "urgency",
                    models.IntegerField(
                        choices=[
                            (1, "Critical - Start Date Today"),
                            (2, "High - Start Date This Week"),
                            (3, "Normal - Start Date Next Week"),
                            (4, "Low - Start Date Next Month"),
                            (5, "Planning - Future Start Date"),
                        ],
                        default=3,
                        help_text="1 = Critical, 5 = Planning",
                        verbose_name="Urgency",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed information about the onboarding requirements",
                        verbose_name="Description",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for HR team (not visible to hiring manager)",
                        verbose_name="Internal Notes",
                    ),
                ),
                (
                    "equipment_needed",
                    models.TextField(
                        blank=True,
                        help_text="List of equipment, software, or access needed",
                        verbose_name="Equipment Needed",
                    ),
                ),
                (
                    "completed_tasks",
                    models.TextField(
                        blank=True,
                        help_text="List of completed onboarding tasks",
                        verbose_name="Completed Tasks",
                    ),
                ),
                (
                    "pending_tasks",
                    models.TextField(
                        blank=True,
                        help_text="List of remaining onboarding tasks",
                        verbose_name="Pending Tasks",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when onboarding was completed",
                        null=True,
                        verbose_name="Completion Date",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        default=onboarding.models.mk_secret,
                        max_length=36,
                        verbose_name="Secret key for external access",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department handling this onboarding request",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "hr_coordinator",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR team member responsible for this onboarding",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_onboarding_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="HR Coordinator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Request",
                "verbose_name_plural": "Onboarding Requests",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Brief title for this update",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Detailed progress update or notes",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this update is visible to the hiring manager",
                        verbose_name="Visible to Hiring Manager",
                    ),
                ),
                (
                    "new_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Pending"),
                            (2, "In Progress"),
                            (3, "Waiting for Information"),
                            (4, "Completed"),
                            (5, "Cancelled"),
                        ],
                        help_text="If status was changed, what was it changed to?",
                        null=True,
                        verbose_name="New Status",
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        blank=True,
                        help_text="Time spent on this update",
                        null=True,
                        verbose_name="Time Spent",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="onboarding.onboardingrequest",
                        verbose_name="Onboarding Request",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made this update",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Update",
                "verbose_name_plural": "Progress Updates",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this onboarding template",
                        max_length=100,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "position_types",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of position types this template applies to",
                        max_length=200,
                        verbose_name="Position Types",
                    ),
                ),
                (
                    "checklist_items",
                    models.JSONField(
                        default=list,
                        help_text="List of standard checklist items for this type of onboarding",
                        verbose_name="Checklist Items",
                    ),
                ),
                (
                    "required_equipment",
                    models.TextField(
                        blank=True,
                        help_text="Standard equipment needed for this position type",
                        verbose_name="Required Equipment",
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        default=5,
                        help_text="Typical number of days to complete this onboarding",
                        verbose_name="Estimated Duration (Days)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is currently in use",
                        verbose_name="Active",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this template applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="onboarding.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Template",
                "verbose_name_plural": "Onboarding Templates",
                "ordering": ["department", "name"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_on_request_assign",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications when assigned new onboarding requests",
                        verbose_name="E-mail me when assigned a request",
                    ),
                ),
                (
                    "email_on_request_update",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications when requests I'm assigned to are updated",
                        verbose_name="E-mail me on request updates",
                    ),
                ),
                (
                    "dashboard_show_pending",
                    models.BooleanField(
                        default=True, verbose_name="Show pending requests on dashboard"
                    ),
                ),
                (
                    "dashboard_show_overdue",
                    models.BooleanField(
                        default=True, verbose_name="Show overdue requests on dashboard"
                    ),
                ),
                (
                    "requests_per_page",
                    models.IntegerField(
                        choices=[(10, "10"), (25, "25"), (50, "50"), (100, "100")],
                        default=25,
                        verbose_name="Requests per page",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Settings",
                "verbose_name_plural": "Onboarding Settings",
            },
        ),
        migrations.CreateModel(
            name="OnboardingAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=1000,
                        upload_to="onboarding/attachments/%Y/%m/",
                        verbose_name="File",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Filename"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME Type"
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True,
                        help_text="Size of this file in bytes",
                        verbose_name="Size",
                    ),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                (
                    "progress_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="onboarding.progressupdate",
                        verbose_name="Progress Update",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["filename"],
            },
        ),
    ]
